export const SINGLE_DATE_SUGGESTIONS = [
  "today",
  "tomorrow",
  "yesterday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
  "next Monday",
  "next Tuesday",
  "next Wednesday",
  "next Thursday",
  "next Friday",
  "next Saturday",
  "next Sunday",
  "last Monday",
  "last Friday",
  "in 2 days",
  "in 3 days",
  "in 5 days",
  "in a week",
  "in 2 weeks",
  "in a month",
  "in 3 months",
  "in 6 months",
  "in a year",
  "2 days ago",
  "3 days ago",
  "a week ago",
  "2 weeks ago",
  "a month ago",
  "a year ago",
  "May 20",
  "December 25",
  "January 1, 2027",
  "March 15",
] as const

export const RANGE_SUGGESTIONS = [
  "this week",
  "next week",
  "last week",
  "this weekend",
  "next weekend",
  "this month",
  "next month",
  "last month",
  "this year",
  "next year",
  "last year",
] as const
